apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "payment-service.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.config.PORT | quote }}
  SERVICE_NAME: {{ .Values.config.SERVICE_NAME | quote }}
  DB_HOST: {{ .Values.config.DB_HOST | quote }}
  DB_NAME: {{ .Values.config.DB_NAME | quote }}
  MQ_URL: {{ .Values.config.MQ_URL | quote }}
  ACCOUNT_SVC_URL: {{ .Values.config.ACCOUNT_SVC_URL | quote }}
