apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "account-service.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "account-service.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.config.PORT | quote }}
