apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "config-service.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.config.PORT | quote }}
  SERVICE_NAME: {{ .Values.config.SERVICE_NAME | quote }}
  REDIS_HOST: {{ .Values.config.REDIS_HOST | quote }}
  REDIS_PORT: {{ .Values.config.REDIS_PORT | quote }}
